### ISSUE TITLE
Read arrow files

### ISSUE THREAD

**Issue by SPChytas** [mistyreed63849/Graph-LLM#5]
Hello and congratulations on your work. I noticed some .arrow files in your dataset which, I assume, correspond to the graphs that were used in your experiments. Is it possible to provide us also with the script you used to read these files? 
If these files do not correspond to the used graphs, is it possible to upload them too?

**Comment by mistyreed63849** [comment]
Hello @SPChytas ,

Thanks for your interest in our project!
The `.arrow` file in every dataset, together with `dataset_info.json` and `state.json`, stores the nodes' textual feature, and it is loaded when calling the function `datasets.load_from_disk`. An example is in `utils/dataset.py`:
```python
# line 11
dataset = datasets.load_from_disk(f"{module_path}/dataset/sp")
```
All the graphs used during our experiment are in the google drive link.
If you have further questions, please feel free to ask.

**Comment by SPChytas** [comment]
Ok, I see. Thanks! However, your `dataset.zip` contains only 5 files per folder: the `.arrow` along with the two `.json` files, as well as the split information `_split.pkl` along with a tensor that stores the edges `_edges.pkl`. From these files, it is not obvious how to recover the graphs you used in your training. In your paper, you mention (Table 1) that you operate on graphs with about 15-20 nodes. These graphs are not present in your `.zip` file.

**Comment by mistyreed63849** [comment]
Hi @SPChytas ,
In each folder, 10000 graphs (including training, validation and test) are stored in the 5 files you mentioned. Nodes and edges of different graphs are stored in the same files together. You may debug in `utils/dataset.py` to see how the graph instances are loaded, and in `train_graph_llm.py` to see how the graphs are split into 3 sets:
```python
    #line 87-90 in train_graph_llm.py
    train_dataset = clm_dataset_train.select(split['train'])
    val_dataset = clm_dataset_train.select(split['valid'])
    val_dataset_eval = clm_dataset_test.select(split['valid'])
    test_dataset = clm_dataset_test.select(split['test'])
```
Note that for each dataset, or say folder, the nodes in 10000 graph instances are indexed consecutively, like 0-14 for the first graph, and 15-29 for the second, and so on.
I hope the response can address your question. If you have further questions, please feel free to ask.

**Comment by SPChytas** [comment]
Thanks, this clarifies everything! My confusion had to do with the node indexing.
