### ISSUE TITLE
Maximum Triplet Sum -- labels

### ISSUE THREAD

**Issue by SPChytas** [mistyreed63849/Graph-LLM#6]
Hello, is it possible to provide some extra information about how you created the labels of the MTS task? Specifically, about 93% of the labels have the value -90, although the max triplet sum is clearly a positive number. Did you use these labels during training or is there a mistake in the uploaded dataset?

**Comment by mistyreed63849** [comment]
Hi @SPChytas ,
Thank you for your interest in our project!
Actually, for each graph, we only take one node as the central node to calculate the max triplet sum, and all other nodes in the graph are labeled as illegal values. We only use the label of central node during training and evaluation. Besides MTS, similar processing occurs in other datasets.
If you have further questions, please feel free to ask.
